In [1]:
import pandas as pd
DataUrl = 'https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv'
df = pd.read_csv(DataUrl)
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

데이터의 행과 열의 갯수를 출력하라

In [12]:
len(df.columns),len(df)

(5, 4622)

데이터의 컬럼명을 출력하라

In [ ]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

데이터의 인덱스를 출력하라

In [36]:
df.index

RangeIndex(start=0, stop=4622, step=1)

quantity 컬럼 값이 3인 데이터를 추출하여 첫 5행을 출력하라

In [24]:
df.loc[df["quantity"] == 3].head(5)

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
818,338,3,Bottled Water,NaN,$3.27
850,350,3,Canned Soft Drink,[Sprite],$3.75

quantity, item_price 두 개의 컬럼으로 구성된 새로운 데이터프레임을 정의하라

In [39]:
df1= df[["quantity","item_price"]]
df1

      quantity item_price
0            1     $2.39
1            1     $3.39
2            1     $3.39
3            1     $2.39
4            2    $16.98
...        ...        ...
4617         1    $11.75
4618         1    $11.75
4619         1    $11.25
4620         1     $8.75
4621         1     $8.75

[4622 rows x 2 columns]

item_price 컬럼의 달러 표시 문자($)를 제거하고 float 타입으로 저장하여 new_price 컬럼에 저장하라

In [ ]:
df["new_price"] = df["item_price"].str.replace("$","").astype(float)

4622

new_price 컬럼이 5 이하의 값을 가지는 데이터프레임을 추출하고, 전체 갯수를 구하여라

In [52]:
len(df[(df["new_price"]<=5)])

1652

item_name이 'Chicken Salad Bowl'인 데이터프레임을 추출하고 index를 초기화하라

In [54]:
df[df["item_name"]=="Chicken Salad Bowl"].reset_index()

,index,order_id,quantity,item_name,choice_description,item_price,new_price
0,44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
1,135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50,22.50
2,213,94,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$22.50,22.50
3,256,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
4,315,137,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$17.50,17.50
...,...,...,...,...,...,...,...
105,4561,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$17.50,17.50
106,4580,1822,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",$11.25,11.25
107,4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
108,4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
109,4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

new_price 값이 9 이하이고 item_name이 'Chicken Salad Bowl'인 데이터프레임을 추출하라

In [58]:
df[(df["new_price"]<=9) & (df["item_name"] == "Chicken Salad Bowl" )].head()

,order_id,quantity,item_name,choice_description,item_price,new_price
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
256,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
526,220,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Sour ...",$8.75,8.75
528,221,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
529,221,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75

데이터를 new_price 컬럼 기준으로 내림차순 정렬하고 첫 5행을 출력하라

In [66]:
df.sort_values("new_price",ascending= False).head(5)

,order_id,quantity,item_name,choice_description,item_price,new_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75

df의 item_name 종류는 몇 개인지 출력하라

In [69]:
df["item_name"].nunique()

50

item_name별 등장 횟수를 내림차순으로 출력하라 (상위 10개)

In [73]:
df["item_name"].value_counts().head(10)

item_name
Chicken Bowl                    726
Chicken Burrito                 553
Chips and Guacamole             479
Steak Burrito                   368
Canned Soft Drink               301
Steak Bowl                      211
Chips                           211
Bottled Water                   162
Chicken Soft Tacos              115
Chips and Fresh Tomato Salsa    110
Name: count, dtype: int64

가장 많이 주문된 item_name 1개를 출력하라

In [74]:
df["item_name"].value_counts().head(1)

item_name
Chicken Bowl    726
Name: count, dtype: int64

quantity의 합계는 얼마인가?

In [76]:
df["quantity"].sum()

4972

new_price의 평균은? (소수점 2자리까지)

In [81]:
a = df["new_price"].mean()
f'{a:.2f}'

'7.46'

item_name별 quantity의 합을 내림차순으로 정렬하여 상위 5개를 출력하라

In [91]:
a = df.groupby("item_name")["quantity"].sum()
a.sort_values(ascending=False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

item_name별 new_price의 평균을 내림차순으로 정렬하여 상위 5개를 출력하라

In [92]:
a = df.groupby("item_name")["new_price"].mean()
a.sort_values(ascending=False).head()

item_name
Bowl                     14.800000
Steak Salad Bowl         11.847931
Chicken Salad Bowl       11.170455
Carnitas Crispy Tacos    11.137143
Carnitas Salad Bowl      11.056667
Name: new_price, dtype: float64

choice_description 컬럼의 결측치 갯수를 구하여라

In [95]:
df["choice_description"].isnull().sum()

1246

choice_description의 결측치를 'NoData'로 채워라

In [ ]:
df["choice_description"] = df["choice_description"].fillna("NoData")

item_name이 'Izze'인 데이터를 'Fizzy Lizzy'로 바꾸어라

In [ ]:
df["item_name"] = df["item_name"].replace("Izze", "Fizzy Lizzy")

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75